### PR TITLE
Use symbolic log level definitions instead of numbers

### PR DESCRIPTION
**Pull request by mglae**
With Kodi PR [Remove LOGNOTICE and LOGSEVERE from python addons and kodi](https://github.com/xbmc/xbmc/pull/18346) the log level numbers will change. Fix setting addon by using symbolic log levels.

Most work was done by:
```
find src -name "*.py" -print0|xargs -0 sed -i 's/\([^ ]*\.\)\?\(dbg_log(.*, \)0)/\1\2\1LOGDEBUG)/'
find src -name "*.py" -print0|xargs -0 sed -i 's/\([^ ]*\.\)\?\(dbg_log(.*, \)1)/\1\2\1LOGINFO)/'
find src -name "*.py" -print0|xargs -0 sed -i 's/\([^ ]*\.\)\?\(dbg_log(.*, \)2)/\1\2\1LOGWARNING)/'
find src -name "*.py" -print0|xargs -0 sed -i 's/\([^ ]*\.\)\?\(dbg_log(.*, \)4)/\1\2\1LOGERROR)/'
# find and print multi line dbg_log()
find src -name "*.py" -print0|xargs -0 grep -ne 'dbg_log(.*[^)]$'
```

This PR needs #160 to be committed first.

### CODE REVIEW

**Comment by mglae** [comment]
Rebased to master.

Is the 9.2 backport wanted?
Pro: future backports are easier.
Cons: the backport is technically not needed.

**Comment by edit4ever** [comment]
Thanks for the rebase - I will test this.  I don't think we need to backport as "if it ain't broke...".  :-)

Of course - if anyone else feels differently - feel free to chime in!

**Comment by mglae** [comment]
Agree.

After testing and merging we have to update the settings addon in LE master. Kodi was updated yesterday.

**Comment by edit4ever** [comment]
Unfortunately I haven't been able to get a completed build with current LE master so I haven't been able to test yet.

Soon as I sort out what's up with the kodi update that's crashing my build I'll get back to this.

**Comment by edit4ever** [comment]
@mglae Finally got my build up - while testing this PR (which seems fine) I came across this error in the logs:

[kodi.log](https://github.com/LibreELEC/service.libreelec.settings/files/5233919/kodi.log)

Are you seeing this?  It is on current master on generic build.

**Comment by mglae** [comment]
Unfortunately yes - after updating yesterday from Milhouse 0717 to nightly-20200915.

Most likely Python3 update from 3.7.8 to 3.8.5

Second FATAL can be fixed by by `objXmlFile = open(self.KEYBOARD_INFO, 'r', encoding='utf-8')`.

For the `import gobject` exception the only idea is to try bumping the related libraries

**Comment by HiassofT** [comment]
concerning the gobject error: we are using the ancient pygobject2 version - guess we have been lucky that it worked with python 3 at all.

As dbus-python which uses dbus-glib both have been deprecated for some time (see https://www.freedesktop.org/wiki/Software/DBusBindings/) we need to switch to more modern python/dbus bindings.

[pydbus](https://github.com/LEW21/pydbus) is listed as an alternative, but that doesn't seem to be too actively maintained.

GDbus via PyGi bindings are another alternative, though that still pulls in glib and we'd need the nasty glib introspection stuff.

[dbussy](https://github.com/ldo/dbussy) sounds interesting, it's a rather new implementation that uses modern Python 3 features

As I'm not a python developer I'll let you evaluate which route to go

**Comment by edit4ever** [comment]
Unfortunately I'm not a python developer either - I just got circled in as I worked on the GUI aspects (learning python as I went) when I had free time.
@mglae does your experience lend itself to evaluating a dbus replacement?

**Comment by mglae** [comment]
I will have a look on it.

Can this PR be merged now? I like to push the FATAL fix below.

**Pull request merged**
