### PR TITLE
f-strings conversion

### PR DESCRIPTION
**Pull request by antonlacon**
Python has multiple ways to combine strings and variables:

`print("Some Var's value is: %s" % SOME_VAR)`
`print("Some Var's value is: " + SOME_VAR)`
`print("Some Var's value is: {}".format(SOME_VAR))`
`print(f"Some Var's value is: {SOME_VAR}")`
(and probably some others that I haven't used)

The addon uses a blend of the first two styles. The examples above are purposefully simple, but they can get complicated to maintain. This PR converts most usage to the 4th option, known as an f-string, which is easiest to read in my opinion. Functionally, they're identical so it comes down to what others prefer to use. Assuming others agree, f-strings have the added benefit of being the fastest method of formatting strings.

Draft because while this should be complete, and I've been using it since June/July, I'm certain there are elements of the addon I don't use.

### CODE REVIEW

**Comment by heitbaum** [comment]
@antonlacon these changes are working. Can this be pulled into master?

@CvH - would be good to get this in as pre-req for ravel and dbussy

**Comment by thoradia** [comment]
@antonlacon @CvH @heitbaum 
I will not be able to rebase #189 on top of this
Incidentally, #189 introduces the @config.log_function decorator with which does away with most of the function log strings
```
def f(args):
    try:
        oe.dbg_log(...)
        commands
        oe.dbg_log(...)
    except Exception as e:
        self.oe.dbg_log(...)
```
can be simplified to
```
@config.log_function
def f(args):
    commands
```
No strings!

**Comment by CvH** [comment]
@antonlacon pls rebase

**Comment by antonlacon** [comment]
Rebased.

**Review by thoradia — COMMENTED** [review]
I have taken care of the reg* lines in connman.py in #191
I will pick up the remaining change of connman.py in #191, so you can drop you commit for connman.py

**Pull request merged**
