### PR TITLE
oe.py cleanup pass

### PR DESCRIPTION
**Pull request by antonlacon**
This cleanup pass does: 

converts bluetooth.py to use log.log
converts oe.py and oeWindows.py to use the log.log_function decorator / log.log
removes oe.dbg_log
cleanup other oe.py functions

Everything should still be working in the same general way. No intentional changes were made to how functions were used. I've tested some of the addon, but I don't use all of its features so issues may be lurking.

### CODE REVIEW

**Comment by antonlacon** [comment]
Added two commits for uniform copyright header information (LE's website) in all files, and to remove an unused function (oe.enable_service).

**Comment by lrusak** [comment]
Looking at the diff with whitespace changes hidden makes the change set much more reviewable.
https://github.com/LibreELEC/service.libreelec.settings/pull/286/files?w=1

**Comment by antonlacon** [comment]
I've added an execute replacement branch. It's located in os_tools here. Some previous oe.execute calls have been converted to straight python (file copies / deletions mostly). The RTC / RPI_CPU_VER are to correct errors that popped up after making os_tools.execute() noisier when a command fails.

**Comment by antonlacon** [comment]
Is this in anyone's test builds?

**Pull request merged**
