### PR TITLE
Convert overlooked numeric log levels / Move status logs from LOGERROR to LOGINFO

### PR DESCRIPTION
**Pull request by mglae**
Follow up to #173 

Fix for a real error: Today log level 4 is LOGFATAL, but LOGERROR is needed here.

### CODE REVIEW

**Comment by mglae** [comment]
Added commit to move log level of two additional status messages from LOGERROR to LOGINFO (not worth an own PR)

**Review by antonlacon — APPROVED** [review]

**Comment by CvH** [comment]
@mglae can you rebase btw have a look if it still is okay with the current changes ?

**Comment by thoradia** [comment]
No need to rebase, I will pick it up

**Comment by mglae** [comment]
Is rebased.

@thoradia No need to waste your time.

**Pull request merged**
