### PR TITLE
Add icon for VPN

### PR DESCRIPTION
**Pull request by cdu13a**
Now that wireguard support has been added to LibreELEC the network connection dialogs should have an icon for vpn connections. 

I created the icon by combining elements of the existing icons, to both maintain similar visual appearance and to make sure that there wasn't any issues with the source of the icon.

### CODE REVIEW

**Comment by chewitt** [comment]
Can I ask you to share a mock-up of the icon without the padlock? ..viewing from the couch at 3m  it took me a minute to realise it was a padlock not a shared folder (similar colouring) so I think the icon would be clearer without it. Otherwise tested and working - it's been an overlooked item on my to-do list for a while so thanks for sending.

**Comment by cdu13a** [comment]
Unfortunately with a 48x48 icon it's a problem you run into.

Here are some alternative icons.
vpn7
vpn6

And a side by side of them in use.
screenshot_vpn

**Comment by chewitt** [comment]
The third one down is simplest/clearest, but I now realise we're assuming all VPN connections are based on wired connections. To make it connection netural, how about the globe icon on its own (shave the LAN bits off) with either VPN text (centred, current is a little low/left of centre) or the padlock icon with a little background shadow against the globe background? - Google search for "VPN icon" and you do see lots of globes with padlocks.

The other thing missing is the "Interface wgX" text underneath the connection name. Can that be read and populated from DBUS?

**Comment by cdu13a** [comment]
A few more options for the icon.
screenshot000_vpndb

The Interface value does not seem to be provided via DBUS. State, and Type have issues as well. Type may end up reading manual or fixed depending on if it's a newly configured vpn, and State may end up reading idle or disconnect when vpn is not connected depending on if you have connected to the vpn before.

At least with an icon in place, it won't look as rough while the rest of the GUI elements for managing a wireguard vpn are finished.

**Comment by chewitt** [comment]
I think "globe with padlock" works best for me as it avoids repetition of "VPN" when connection names also contain it, but Globe with VPN text also looks fine. Up to you.. please pick one and ping me to merge. Backport for the 9.2 branch would be appreciated too. Thanks.

**Comment by cdu13a** [comment]
@chewitt I replaced the icon with the "globe and padlock" one that you liked and opened a PR for the backport of this commit.

**Comment by chewitt** [comment]
thanks!

**Pull request merged**
