### PR TITLE
Properly fix duplicate bluetooth devices

### PR DESCRIPTION
**Pull request by croniccorey**
This reverts the previous PR #124 and properly fixes the bluetooth issue. 

sorry guys i missed the fact i broke stuff but i have fixed it properly now.

### CODE REVIEW

**Comment by croniccorey** [comment]
Hold off on merge with this as well, i made PR to fast since other was merged but i am testing it further to be sure i got issue solved this time

**Comment by croniccorey** [comment]
I have tested this properly now and updated to address any issues i found.

Good to merge, again sorry about the mistake in first PR was broken somewhat :)

**Comment by croniccorey** [comment]
This is good to merge now, i tested it heavily this time to ensure there was no regressions.
sorry about first PR for bluetooth, i should have tested it more first.

Cheers guys

**Comment by MilhouseVH** [comment]
I'll include this PR in my nightly test builds, let's see how it goes for a few days before merging.

**Comment by croniccorey** [comment]
Thanks for testing, I found a case where duplicates can still happen and it made me take a different approach i feel is a better solution, i will be updating PR once i am satisfied with my testing.

Issue - If add-on is left open for a very long time duplicates can happen.

Upon realizing what is actually happening i have made it so listItems is not checked and list is rebuilt every time menu_connections() is called if any device is found.

**Comment by croniccorey** [comment]
I am done with this PR now, any issues with it please let me know.

**Pull request merged**
