### PR TITLE
use prettyname_regex to show shortname in update menu

### PR DESCRIPTION
**Pull request by lrusak**
I'm not 100% happy about this but it does work. It does it in a workaround way though

Instead of tracking the object all the way through it first uses the regex on the filenames to get the short filenames, then when one of the short filenames is chosen it takes that short name and scans the list of long filenames to find a match, which may not be 100%. We have set filenames though and it shouldn't be a problem I don't think.

This was the only way I could think of doing it because `self.struct['update']['settings']['Build']['values']` needs to be a list, so I cannot pass a dict to it to track a prettyname and a filename for one object.

@MilhouseVH please include this in your testbuilds, it will work for you already because you include `prettyname_regex` already in your releases.json

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks very much for this, it seems to be working!

Is there anything that can be done when showing the current version on the confirmation dialog?

Currently it shows the following:
s1

when the following would be better:

```
Current Version: #1108
New Version: #1107
Would you like to update LibreELEC now?

         [Yes]   [No]
```

**Comment by lrusak** [comment]
@MilhouseVH so the problem is that there is no way to store a regex on the system for the current version (at least not in a nice way). So there is no way to parse accurately what build the people are on currently, only what they will be updating to.

What I could do is use the current regex on the current version and if it returns something then use that otherwise just return the entire version string.

How does that sound?

**Comment by MilhouseVH** [comment]
Ah yes, that's true, good point.

Your suggestion would work for me. I could make the regex I use more specific if it returns false matches.

**Comment by MilhouseVH** [comment]
I haven't had any negative feedback - good to merge?

**Comment by lrusak** [comment]
I squashed it, if you're happy I'm happy :)

**Pull request merged**
