### PR TITLE
Fix backup creation

### PR DESCRIPTION
**Pull request by antonlacon**
This resolves 

ERROR <general>: SETTINGS: system.do_backup # AttributeError("'system' object has no attribute 'backup_dlg'")

when creating a backup.

My understanding is that certain variables are being used between functions, but functions are treating them as local to their function.

While not in the error, self.backup_file, self.total_backup_size, and self.done_backup_size are all used to report progress in the dialog box, and between functions, so init those too.

oe.timestamp() is a cleanup of a function used in the backup process. time.localtime() uses time.time() as the input time when another input isn't provided, so the `now` variable is useless.

Please test further. My generated backup is <30MB so I don't see much of the dialog box before it is finished. Since this is being tested, please look at #163 which is also about backups.

### CODE REVIEW

**Comment by mglae** [comment]
There is no dialog visible because self.backup_dlg is closed in tar_add_folder().

```
--- a/resources/lib/modules/system.py
+++ b/resources/lib/modules/system.py
@@ -551,8 +551,9 @@ def tar_add_folder(self, tar, folder):
                     if hasattr(self, 'backup_dlg'):
                         progress = round(1.0 * self.done_backup_size / self.total_backup_size * 100)
                         self.backup_dlg.update(int(progress), f'{folder}\n{item}')
-        finally:
+        except:
             self.backup_dlg.close()
+            raise
 
     @log.log_function()
     def get_folder_size(self, folder):
```

While testing with a slow USB stick as backup target I found we should sync while the dialog is open. i.e.:
```
--- a/resources/lib/modules/system.py
+++ b/resources/lib/modules/system.py
@@ -455,6 +455,8 @@ def do_backup(self, listItem=None):
                 for directory in self.BACKUP_DIRS:
                     self.tar_add_folder(tar, directory)
                 tar.close()
+                self.backup_dlg.update(100, 'Syncing ...')
+                os.sync()
         finally:
             self.backup_dlg.close()
             self.backup_dlg = None
```

(But obviously with using oe._(XXXXX) instead of 'Syncing ...')

**Comment by antonlacon** [comment]
Thanks for reviewing, and updated.

I don't know the process for the string to end up in the other localizations.

**Comment by mglae** [comment]
Add the empty translation to all languages (you have to fix en_gb after that):
```
for i in $(find resources/language/ -name "*.po"); do
    cat >>$i <<EOF

msgctxt "#32401"
msgid "Syncing Disks..."
msgstr ""
EOF
done
```

Feel free to start translation.

**Comment by antonlacon** [comment]
Updated with empty strings and Spanish translation.

**Pull request merged**
