### PR TITLE
move old openelec settings config for migration

### PR DESCRIPTION
**Pull request by lsellens**
This is not tested

### CODE REVIEW

**Comment by chewitt** [comment]
@lsellens: Can you modify this to a copy instead of move please. It's probable that some users will flip-flop between OE and LE for a while so we shouldn't remove the OE settings. Thanks.

**Comment by lsellens** [comment]
will do.

**Comment by chewitt** [comment]
NB: Change things, then use git rebase to squash the commits, then force push the changes to update the current PR. It saves closing and re-submitting. We can walk you through it if you're not familiar.

**Comment by lsellens** [comment]
Ok, will do next time. I've already reverted this on my branch and made the corrections.

**Pull request closed without merging**
