### PR TITLE
Remove Estuary specific elements

### PR DESCRIPTION
**Pull request by edit4ever**

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Is this ready to go in now?

**Comment by edit4ever** [comment]
This can go in - just keep in mind that it takes away the top bar in the LE settings since that bar doesn't exist in other skins.  It's the breadcrumbs and clock bar - so technically, it just gives an error on other skins, but I don't believe it causes any problems if we don't change it.  The Kodi team didn't want to add the conditional variable for skin name - so the only option left was to take out the Estuary specific calls to the top/bottom bars.

**Comment by MilhouseVH** [comment]
It would be better to rename this PR and squash the commits before we merge it as the PR description no longer accurately describes what is happening here - the first commit did add conditional Estuary calls, but these were then removed by the second commit. Ultimately this entire PR seems to be removing the breadcrumb labels and (no longer) has anything to do with Estuary or conditionals.

If you can update the description and squash the commits I'll merge this so we can get it into master and also `libreelec-9.2`.

**Comment by edit4ever** [comment]
done.  :-)

**Comment by MilhouseVH** [comment]
Thanks!

**Pull request merged**
